function image = Bits_to_Image(bit_sequence,height,width)
% Function that reads an image from a file and converts it into a bit
% sequence generated by using the macrosymbols containing 2x2 pixels
% input:
% bit_sequence: the bits representing the image
% height: the height of the image
% width: the width of the image
% output:
% image: the image formed by a matrix of bits

image = logical(zeros(height,width));
index = 1;
bit_sequence = [bit_sequence zeros(1,height*width-size(bit_sequence,2))];
for m=1:2:height
    for n=1:2:width
        image(m,n) = bit_sequence(index);
        image(m,n+1) = bit_sequence(index+1);
        image(m+1,n) = bit_sequence(index+2);
        image(m+1,n+1) = bit_sequence(index+3);
        index = index + 4;
    end
end

end