function bit_sequence = Image_to_Bits(image)
% Function that converts an image into a bit sequence generated by using 
% the macrosymbols containing 2x2 pixels
% input:
% image: the image formed by a matrix of bits
% output:
% bit_sequence: the bits representing the image

[height,width] = size(image);
bit_sequence = zeros(1,height*width);
index=1;
for m=1:2:height
    for n=1:2:width
        bit_sequence(index) = image(m,n);
        bit_sequence(index+1) = image(m,n+1);
        bit_sequence(index+2) = image(m+1,n);
        bit_sequence(index+3) = image(m+1,n+1);
        index = index + 4;
    end
end

end